### ISSUE TITLE
Add a more prominent link to the GitHub project

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct.org#111]
The link to the project is currently under "Source Code" if someone searches for "GitHub" they won't find anything.

**Comment by karuppiah7890** [comment]
Something like `Source Code on GitHub` could be something to consider too. Or the usual GitHub icon on the top right corner of the web page

**Comment by filiphr** [comment]
I didn't think about `Source Code on GitHub` and I forgot about the usual GitHub icon on the top right corner 😄.

Thinking a bit more about it, I think that something like what junit.org has with the `Code & Issues` would be the best. It can be in the best.

I think it is easy to do it. I'll give it a go

**Comment by filiphr** [comment]
Did this in https://github.com/mapstruct/mapstruct.org/commit/1f7b63db542762eceefc7e7eddadf87619ede695
