### ISSUE TITLE
Broken links in TOC of MapStruct site FAQ

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct.org#124]

**Comment by jccampanero** [comment]
Sorry @filiphr, unintentionally I removed the pull request and the fork. 

Thank you very much for your comments, I appreciate that.

I agree with you, the proposed solution in addition solves the problem related with the references to `ambiguous` and `qualifier` in the code of the library.

I'm sorry I can't contribute to the project this time around. Hope to be of more help next time.

**Comment by filiphr** [comment]
>Sorry @filiphr, unintentionally I removed the pull request and the fork.

You didn't remove the PR. It is still under #123. You only removed your branch and fork.

As I said, thanks a lot for making us aware about the problem, that is a great contribution.

**Comment by jccampanero** [comment]
You are welcome @filiphr, thank you for your kind words.
