### ISSUE TITLE
How to copy attributes of the same class using Mapstruct

### ISSUE THREAD

**Issue by YAGAMIL** [mapstruct/mapstruct.org#127]
`Car copyIn(Car source, Car target)`

I need to copy non-null attributes from source to target. How to use matstruct to do this

**Comment by filiphr** [comment]
Please do not use the issue tracker for asking questions. 

If you need to ask questions you can ask them on
* [StackOverflow](https://stackoverflow.com/questions/tagged/mapstruct)
* [Gitter Room](https://gitter.im/mapstruct/mapstruct-users)
* [Discussions](https://github.com/mapstruct/mapstruct/discussions)
