### ISSUE TITLE
Do I have to use Mapstruct with Lombok? I didn't introduce Lombok into my project. I wrote get and set manually, but it reminded me that I couldn't find attributes.

### ISSUE THREAD

**Issue by xhyym** [mapstruct/mapstruct.org#128]
Do I have to use Mapstruct with Lombok? I didn't introduce Lombok into my project. I wrote get and set manually, but it reminded me that I couldn't find attributes.

**Comment by filiphr** [comment]
This is not a MapStruct question. This is entirely up to you to decide whether you want to use Lombok or not in your own project.

**Comment by xhyym** [comment]
Thank you very much for your answer, so mapstruct doesn't have to be used with Lombok, I just need to write the getter and setter for each property, right?
