### ISSUE TITLE
Provide an Eclipse update site for the plug-in on mapstruct.org

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct.org#17]
@larswetzer DYT you could create an update site which we can publish on the web site until we have the plug-in in the market place?

**Comment by larswetzer** [comment]
Sure, we can Tycho let do the job to build a p2 repository.

**Comment by filiphr** [comment]
Forgot about this issue, but we already did this in https://github.com/mapstruct/mapstruct.org/commit/60b9c78b637e036dbe5bc3e73f73be114545f425.
