### ISSUE TITLE
Chapter 12: specify @Qualifier import

### ISSUE THREAD

**Issue by pgonday** [mapstruct/mapstruct.org#19]
I think it could be useful to specify that @Qualifier import is org.mapstruct.Qualifier
In my project, I made the mistake of importing javax.inject.Qualifier which leads to the error message "Ambiguous mapping method..."

**Comment by gunnarmorling** [comment]
Ah, yes, that's a good idea. Would you mind sending a pull request for
fixing it? Thx!

**Comment by filiphr** [comment]
@gunnarmorling This is an old request. I see that the initial idea was to add an import in the documentation. We still don't have it in there. Do you think we need to add it there, or we could do it in an FAQ?

**Comment by gunnarmorling** [comment]
I think that's better done in the documentation.

**Comment by filiphr** [comment]
I have moved this to https://github.com/mapstruct/mapstruct/issues/1109, as the documentation is part of that repository.

I'll close this one

**Comment by gunnarmorling** [comment]
Thanks!
