### ISSUE TITLE
Documentation Contents Section is not vertically scrollable

### ISSUE THREAD

**Issue by eng-Robert** [mapstruct/mapstruct.org#28]
In [Documentation Page](http://mapstruct.org/documentation/) , the contents section on the right is not vertically scrollable. On a 15'' wide screen, the screen height is not big enough to hold all the items; the contents section is cropped on point 15.

**Comment by gunnarmorling** [comment]
Hi @eng-Robert, thanks for pointing out this issue! We've converted the documentation into the AsciiDoc format now, which also fixes this problem.

You can find the guide in the new format here: http://mapstruct.org/documentation/1.0/reference/html/
