### ISSUE TITLE
Changerequest: EnumNamingStrategy

### ISSUE THREAD

**Issue by maposchmi** [mapstruct/mapstruct.org#31]
We had to map a lot of jaxb-types with the default-naming-strategy of jaxb (underscores to triple-underscores, ...) and didnt want to map all the Enum manually by the Mapping-annotation.

So we introduced EnumNamingStrategy, simmilar to AccessorNamingStrategy.

[mapstruct-1.0.1-modified.zip](https://github.com/mapstruct/mapstruct.org/files/205854/mapstruct-1.0.1-modified.zip)

We also fixed a typo.

**Comment by agudian** [comment]
Please open up a pull-request in the repository mapstruct/mapstruct and create an issue there describing the feature and it's purpose. It's then much easier to discuss that and any code changes.

Thanks!

(I'm gonna close thos here, as it is the wrong repository)
