### ISSUE TITLE
<ANY_UNMATCHED> is used in place of <ANY_UNMAPPED> in section 7.1 Mapping enum types

### ISSUE THREAD

**Issue by agalchavijaycalls** [mapstruct/mapstruct.org#34]
MapStruct also has a mechanism for mapping any remaining (unspecified) mappings to a default. This can be used only once in a set of value mappings. It comes in two flavors: `<ANY_REMAINING>` and _**`<ANY_UNMATCHED>.`**_

**Comment by agudian** [comment]
Thanks for the info! I've fixed the typo in the html documentation on the website and in the sources for the next release.
