### ISSUE TITLE
@Mapping generates compilation errors on Maven/Netbeans

### ISSUE THREAD

**Issue by olabomba** [mapstruct/mapstruct.org#40]
Hi,
I'm using jhipster, which generates mapstruct mappings.
I've errors on certain fields (not all of them), if they have multiple @Mapping annotation. Only in the EDI. All building process, by maven, is OK.
The error is : "Incompatible types: int cannot be converted to boolean".
Have you any idea ?
Thanks,
Regards.

**Comment by gunnarmorling** [comment]
Can you please close this issue and re-open it in the "mapstruct" repo?
This project here and its tracker is for the mapstruct.org website only.

Can you also add the definition of the mapper interface (or maybe a
screenshot indeed if it only happens within NetBeans). Thanks!

**Comment by olabomba** [comment]
Ok, excuse me :)
