### ISSUE TITLE
Set up analytics for reference guide and API docs

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct.org#44]

**Comment by gunnarmorling** [comment]
Hey @filiphr, given your mastering of sed recently, would you possibly be interested in giving this a try? It probably makes sense to add this to the publish script. The GA id is stored in the config.toml file, the snippet to insert can be found in any of the HTML pages.

**Comment by filiphr** [comment]
No problem @gunnarmorling. I'll give it a try tonight

**Comment by gunnarmorling** [comment]
Done. Thanks, Filip!
