### ISSUE TITLE
Add an F&Q about @Mapper not found

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct.org#49]
It seems that there is a problem when both `mapstruct` and `mapstruct-jdk8` are found on the classpath. See longer discussion in [mapstruct#841](https://github.com/mapstruct/mapstruct/issues/841). A known problem is the compile dependency on `mapstruct` in [springfox-swagger](http://mvnrepository.com/artifact/io.springfox/springfox-swagger2). I think having this question and an example how to exclude the `mapstruct` dependency is good to have.

**Comment by gunnarmorling** [comment]
Done.
