### ISSUE TITLE
Use latest hugo for website

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct.org#67]
There were some issues when I used a newer version of hugo. Therefore, until now We were using 0.18. The problem was some new property (`disablePathToLower`, which by default is `false`) which caused the paths of the released articles to be lower case. We have fixed this.

In any case we need to add the version of hugo in our `publish.sh` so we are always using a fix version when doing a publish.

**Comment by gunnarmorling** [comment]
+1 for mandating a specific version. Related to this, a great improvement would be to publish the website from Travis automatically after a push to master.

**Comment by filiphr** [comment]
@gunnarmorling completely agree with you 😄. I don't think it would be too complex to add that to the build. However, it would mean that we need to allow Travis to push to our repo, that is OK for you I presume 😉.

**Comment by gunnarmorling** [comment]
Applied the PR.

> However, it would mean that we need to allow Travis to push to our repo, that is OK for you I presume

Yes, it would be ok. I don't know Travis very well, but there's a way for managing secrets such as credentials. We should use a dedicated account with the minimum set of permissions. Let's continue the discussion over at #69 which I just filed.
