### ISSUE TITLE
Assign List Attribute without creating a copy of List

### ISSUE THREAD

**Issue by cathyang12** [mapstruct/mapstruct.org#73]
```
Source : {
     someList: ArrayList<SomeObject>
}

Target: {
     someList: ArrayLIst<SomeObject>
}
```

When I use the mapstruct, it will automatically create a new ArrayList and add the list from source in it. However, I just want to use the usual mapping (I want them to point to the same memory location), is there some attribute in mapper that I can configure so that mapstruct will generate
```
target.setSomeList(source.getSomeList()) 
```
?

Thank you very much!

**Comment by twentylemon** [comment]
I just ran into this problem this morning as well! As a workaround, you can define a mapping method for the List itself.

```java
@Mapper
abstract class MyMapper {
    abstract ThingWithList fromOther(OtherThingWithList other);

    protected <T> List<T> doNotCopyList(List<T> list) {
        return list;
    }
}
```

Generates (in 1.2):
```java
List<String> list = doNotCopyList( other.getList() );
if ( list != null ) {
    thingWithList.setList( list );
}
```

**Comment by filiphr** [comment]
Closing this since it has been answered already. For the future please do not use this issue tracker for asking questions
