### ISSUE TITLE
Mapping of Map fields to existing target not working with defensive programming style

### ISSUE THREAD

**Issue by Vicente69** [mapstruct/mapstruct.org#74]
Hi,

I'm working with Mapstruct 1.2.0.Final and I'm using a "defensive" programming style for a Map field in a class, for security reasons. I mean the field getter returns a copy of the field mappings, and the setter copies the given mappings into the field. Typically, this is done with such getter/setter in the class:
```java
private Map<String, Object> properties;

public Map<String, Object> getProperties() {
    return new HashMap<>(this.properties);
}

public void setProperties(final Map<String, Object> properties) {
    this.properties.clear();
    this.properties.putAll(properties);
}
```

Mapping another object to an existing instance of this class doesn't work as I expected, because the field setter in never used in implementations generated by Mapstruct. The code below is actually generated:
```java
target.getProperties().clear();
target.getProperties().putAll(...);
```

To me, this shall be replaced by the policy below:
```java
final Map<String, Object> properties = target.getProperties();
properties.putAll(...);
target.setProperties(properties);
```

I attached a test case in this issue: 
[MappingTest.java.zip](https://github.com/mapstruct/mapstruct.org/files/1710919/MappingTest.java.zip)

Is this feature implemented?
How can I configure/use Mapstruct for such case?
Thanks in advance for your help.
BR

**Comment by Vicente69** [comment]
I must apologize, it seems the `CollectionMappingStrategy.TARGET_IMMUTABLE` setting is dedicated for such case.
Sorry for the inconvenience. I close the issue.

**Comment by filiphr** [comment]
😄 no problem @Vicente69. I am glad that you figured out the usage.
