### ISSUE TITLE
Default to null if empty String

### ISSUE THREAD

**Issue by avk2** [mapstruct/mapstruct.org#80]
Could I configure the mapper to map the target to `null` if the source of a type `String` is empty `""` ?

**Comment by filiphr** [comment]
@avk2 this is not the place to ask questions. Please use [StackOverflow](https://stackoverflow.com/questions/tagged/mapstruct) or our [forum](https://groups.google.com/forum/#!forum/mapstruct-users) for asking questions.

In any case this is currently not possible. However, you can add a custom presence check method in your bean that would return `true` if your string is not `null` and not empty
