### ISSUE TITLE
java.lang.ClassNotFoundException: Cannot find implementation(gradle+sts+springBoot)

### ISSUE THREAD

**Issue by ft0907** [mapstruct/mapstruct.org#85]
I am sorry that this error occurred during the use of mapstruct.
 Environment used ： gradle-4.6    STS 3.9.5   springBoot 2.0.4.RELEASE

plugins {
    id 'java'
    id 'net.ltgt.apt' version '0.9'
}

dependencies {
	compile 'org.mapstruct:mapstruct-jdk8:1.3.0.Beta1'
	compile 'org.mapstruct:mapstruct-processor:1.3.0.Beta1'
}

Referring to the official Web example, implementation classes can be generated, but this error always occurs when I use the injected bean.
I guess it's related to the environmental version I use. Friends who want to know can help answer? Thanks!!! @filiphr

**Comment by filiphr** [comment]
I think that this one is the same as https://github.com/mapstruct/mapstruct-examples/issues/45. Have a look at https://github.com/mapstruct/mapstruct-examples/issues/45#issuecomment-421453225 for the solution

**Comment by BVijayKrishna** [comment]
@filiphr I'm using 1.3.0.Beta2 version of mapstruct with gradle 3.4

plugins {
    id 'net.ltgt.apt' version '0.9'
}

compile "org.mapstruct:mapstruct:1.3.0.Beta2", 
apt "org.mapstruct:mapstruct-processor:1.3.0.Beta2

sourceSets {
   		main.java.srcDirs += "build/generated/source/apt/main"
}

Still I see implementation class is not found. Can you please suggest
