### ISSUE TITLE
 java.lang.ClassNotFoundException: Cannot find implementation for 

### ISSUE THREAD

**Issue by BVijayKrishna** [mapstruct/mapstruct.org#87]
I'm using mapstruct along with lomback with versions as follows

Java 1.8
springBootVersion = '1.4.3.RELEASE'
gradle version 3.4
mapstructVersion 1.3.0.Beta2
lombokVersion 1.18.0

Configurtions added

dependencies {
           classpath('net.ltgt.gradle:gradle-apt-plugin:0.8')
    }

plugins {
id 'net.ltgt.apt' version '0.9'
}
ext {
    mapstructVersion = "1.3.0.Beta2"
    lombokVersion = "1.18.0"
}
apply plugin: 'net.ltgt.apt'

compile "org.mapstruct:mapstruct:${mapstructVersion}", "org.projectlombok:lombok:${lombokVersion}"
    apt "org.mapstruct:mapstruct-processor:${mapstructVersion}", "org.projectlombok:lombok:${lombokVersion}"

sourceSets {
main.java.srcDirs += "build/generated/source/apt/main"
}

Still, I see the implementation class is not found. Can you please suggest

**Comment by filiphr** [comment]
@BVijayKrishna you added comments to 2 different issues and created a new issue for our website. We are following all repositories and there is no need to cross post across our repositories. 

As I've mentioned in another issue, I think that https://github.com/mapstruct/mapstruct-examples/issues/45#issuecomment-421453225 is the solution
