### ISSUE TITLE
cannot generate the implementation for eclipse

### ISSUE THREAD

**Issue by bakeloar** [mapstruct/mapstruct.org#88]
hi I use eclipse Photon (4.8.0) with lombok-1.16.20 mapstruct-1.2.0.Final m2e-apt 1.5.2
jdk 1.8.0_111
the configuration of pom file is
<properties>
    <m2e.apt.activation>jdt_apt</m2e.apt.activation>
</properties>
--
<dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct</artifactId>
      <version>1.2.0.Final</version>
      <scope>compile</scope>
    </dependency>
<dependency>
	<groupId>org.mapstruct</groupId>
	<artifactId>mapstruct-jdk8</artifactId>
</dependency>
--
    <build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<annotationProcessorPaths>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>${org.mapstruct.version}</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>
	</build>

when i run maven build with command “compile” 
I find that  the source folder is created,target\generated-sources\annotations .
but the implementation class  is not found. Can you please help me

**Comment by bakeloar** [comment]
<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct-jdk8</artifactId>
		</dependency>
    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct</artifactId>
      <version>1.2.0.Final</version>
      <scope>compile</scope>
    </dependency>

**Comment by bakeloar** [comment]
build
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<annotationProcessorPaths>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>${org.mapstruct.version}</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>

**Comment by filiphr** [comment]
You might be hitting the same problem as in https://github.com/mapstruct/mapstruct/issues/1159. I think it might be due to the Lombok agent for Eclipse.

**Comment by siripuramjagadishraj1** [comment]
There is a trick:
1. build your maven project.
2. in target\generated-sources copy all the *MapperImpl.java and paste where the *Mapper.java are present
3. Now you wont require to build project again and again. for refresh, ide-restart, etc, etc..
4. but if you want to build project using mvn clean.. again, then undo these changes.
this save a lot of time for me.
