### ISSUE TITLE
final value containers

### ISSUE THREAD

**Issue by kwasny2** [mapstruct/mapstruct.org#92]
I have something like following structure:
class PersonDto {
final Value name = new Value();
final Value surname = new Value();
}

class Value {
...
void set(String value) {
...
}
String get() {
...
}
}

class Person() {
String name;
String surname;
}

Any clue how to map it? From PersonDto to Person, it is relatively easy, hot to do it in revered order. Mind the Values are final.

**Comment by sjaakd** [comment]
please ask questions on StackOverflow.
